### PR TITLE
Fixes problem where mp3s won't load

### PR DESCRIPTION
**Pull request by JKesMc9tqIQe9M**
See the change to the http-options in site.clj -- there is some SSL problem, so if you allow unverified certificates, things work again. Thanks!

### CODE REVIEW

**Comment by JKesMc9tqIQe9M** [comment]
Hi -- no chance of merging this?

**Comment by JKesMc9tqIQe9M** [comment]
Making one final attempt on this one -- thanks.

**Comment by djui** [comment]
Sorry, I'm a bad owner. If you want, I can make you a collaborator, then you can merge yourself?

**Comment by JKesMc9tqIQe9M** [comment]
Thanks! Looks like things are working again. I'd be glad to become a collaborator -- that'd be awesome. I could probably close some of the remaining open issues, since they're redundant now that you merged this PR. Thanks again.

**Pull request merged**
